export default function sitemap() {
  const baseUrl = 'https://oxavyn.com';

  const routes = [
    '',
    '/about',
    '/contact',
    '/careers',
    '/services',
    '/services/web-development',
    '/services/mobile-app-development',
    '/services/custom-software',
    '/services/saas-development',
    '/services/ai-development',
    '/services/generative-ai',
    '/services/machine-learning',
    '/services/data-analytics',
    '/services/business-intelligence',
    '/services/data-science',
    '/services/workflow-automation',
    '/services/crm-automation',
    '/services/business-process-automation',
    '/services/crm',
    '/services/erp',
    '/services/third-party-integrations',
    '/students',
    '/students/internships',
    '/students/foundational-career',
    '/industries',
    '/industries/healthcare',
    '/industries/e-commerce',
    '/industries/education',
    '/industries/retail',
    '/industries/agency-consultancy',
    '/resources',
    '/insights',
    '/blog',
    '/case-studies',
    '/client-success-stories',
    '/help-center',
    '/technology-guide',
    '/faq',
    '/privacy-policy',
    '/terms-and-conditions',
    '/refund-cancellation-policy',
    '/compliance',
  ];

  return routes.map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: 'weekly',
    priority: route === '' ? 1 : 0.8,
  }));
}
